name: npm
on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  install-loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          for i in {1..10000}; do
            npm cache clean --force
            npm install -g @legioncli/cli
            npm uninstall -g @legioncli/cli
          done
